### PR TITLE
fix(BaseInfo.js): Use correct value for Other gender

### LINKED ISSUE #1: Bug: Other is female
https://github.com/Jarmilla/ryuutama-rpg/blob/36e7e20912c4b6888737130cceeaa599ba29519b/ryuutama/src/components/BaseInfo.js#L29

### PR DESCRIPTION
**Pull request by dragonfi**
Fixes #1

### CODE REVIEW

File: ryuutama/src/components/BaseInfo.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ function BaseInfo({ setClass1, setClass2, setType1, setType2 }) {
         <select name="gender selection">
           <option value="male">Male</option>
           <option value="female">Female</option>
-          <option value="female">Other</option>
+          <option value="other">Other</option>
```
Comment (Jarmilla) [inline ryuutama/src/components/BaseInfo.js:29]: thanks

**Review by Jarmilla — APPROVED** [review]
